### ISSUE TITLE
Class `ms_graph` - add `select` argument to the `list_users()` method

### ISSUE THREAD

**Issue by jchrom** [Azure/AzureGraph#27]
Hi all,

so the `/users` resource accepts the [optional `$select`](https://docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&tabs=http#optional-query-parameters) parameter to return the alternative property set. But the `ms_graph` method `list_users()` seems to only include the `filter` and `n` arguments.

Is there a way to supply values for `$select`? I am using the current CRAN version.

**Comment by hongooi73** [comment]
You can work around this by calling the API directly. Modified from the `list_users` source:

```r
opts <- list(`$select`="something")
hdrs <- httr::add_headers(consistencyLevel="eventual")
pager <- ms_graph_pager$new(gr$token, call_graph_endpoint(gr$token, "users", options=opts, hdrs))
extract_list_values(pager, Inf)
```

I'd like to know more about your use case though. AzureGraph is really targeted at data scientists who sometimes need to work with Graph, rather than full-time admins or engineers. I wouldn't think there's much of a need for this community to look at user lists. Can you give me some background about what you're trying to do?
